#pragma once

#include <stdint.h>

enum PX4_CUSTOM_MAIN_MODE {
	PX4_CUSTOM_MAIN_MODE_MANUAL = 1,
	PX4_CUSTOM_MAIN_MODE_ALTCTL,
	PX4_CUSTOM_MAIN_MODE_POSCTL,
	PX4_CUSTOM_MAIN_MODE_AUTO,
	PX4_CUSTOM_MAIN_MODE_ACRO,
	PX4_CUSTOM_MAIN_MODE_OFFBOARD,
	PX4_CUSTOM_MAIN_MODE_STABILIZED,
	PX4_CUSTOM_MAIN_MODE_RATTITUDE,
	PX4_CUSTOM_MAIN_MODE_SIMPLE, /* unused, but reserved for future use */
	PX4_CUSTOM_MAIN_MODE_LCS = 10,
	PX4_CUSTOM_MAIN_MODE_MCS = 11,
	PX4_CUSTOM_MAIN_MODE_HUMAN_STAB = 12,
	PX4_CUSTOM_MAIN_MODE_HUMAN_COG = 13
};

enum PX4_CUSTOM_SUB_MODE_AUTO {
	PX4_CUSTOM_SUB_MODE_AUTO_READY = 1,
	PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF,
	PX4_CUSTOM_SUB_MODE_AUTO_LOITER,
	PX4_CUSTOM_SUB_MODE_AUTO_MISSION,
	PX4_CUSTOM_SUB_MODE_AUTO_RTL,
	PX4_CUSTOM_SUB_MODE_AUTO_LAND,
	PX4_CUSTOM_SUB_MODE_AUTO_RTGS,
	PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET,
	PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND
};

enum PX4_CUSTOM_SUB_MODE_POSCTL {
    PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL = 0,
    PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT
};

enum PX4_CUSTOM_SUB_MODE_LCS {
    PX4_CUSTOM_SUB_MODE_LCS_MANUAL = 1,
    PX4_CUSTOM_SUB_MODE_LCS_STAB = 2
};

enum PX4_CUSTOM_SUB_MODE_MCS {
    PX4_CUSTOM_SUB_MODE_MCS_MANUAL = 1,
    PX4_CUSTOM_SUB_MODE_MCS_STAB = 2
};

union px4_custom_mode {
    struct {
        uint16_t reserved;
        uint8_t main_mode;
        uint8_t sub_mode;
    };
    uint32_t data;
    float data_float;
    struct {
        uint16_t reserved_hl;
        uint16_t custom_mode_hl;
    };
};

struct PX4CustomMode{
    enum Mode : uint32_t{
        MANUAL              = PX4_CUSTOM_MAIN_MODE_MANUAL       <<16,
        STABILIZED          = PX4_CUSTOM_MAIN_MODE_STABILIZED   <<16,
        ACRO                = PX4_CUSTOM_MAIN_MODE_ACRO         <<16,
        RATTITUDE           = PX4_CUSTOM_MAIN_MODE_RATTITUDE    <<16,
        ALTCTL              = PX4_CUSTOM_MAIN_MODE_ALTCTL       <<16,
        OFFBOARD            = PX4_CUSTOM_MAIN_MODE_OFFBOARD     <<16,
        SIMPLE              = PX4_CUSTOM_MAIN_MODE_SIMPLE       <<16,
        POSCTL_POSCTL       = PX4_CUSTOM_MAIN_MODE_POSCTL       <<16 | (PX4_CUSTOM_SUB_MODE_POSCTL_POSCTL      << 24 ),
        POSCTL_ORBIT        = PX4_CUSTOM_MAIN_MODE_POSCTL       <<16 | (PX4_CUSTOM_SUB_MODE_POSCTL_ORBIT       << 24 ),
        AUTO_LOITER         = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_LOITER        << 24 ),
        AUTO_MISSION        = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_MISSION       << 24 ),
        AUTO_RTL            = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_RTL           << 24 ),
        AUTO_FOLLOW_TARGET  = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET << 24 ),
        AUTO_LAND           = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_LAND          << 24 ),
        AUTO_PRECLAND       = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND      << 24 ),
        AUTO_READY          = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_READY         << 24 ),
        AUTO_RTGS           = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_RTGS          << 24 ),
        AUTO_TAKEOFF        = PX4_CUSTOM_MAIN_MODE_AUTO         <<16 | (PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF       << 24 ),
        LCS_MANUAL          = PX4_CUSTOM_MAIN_MODE_LCS          <<16 | (PX4_CUSTOM_SUB_MODE_LCS_MANUAL         << 24 ),
        LCS_STAB            = PX4_CUSTOM_MAIN_MODE_LCS          <<16 | (PX4_CUSTOM_SUB_MODE_LCS_STAB           << 24 ),
        MCS_MANUAL          = PX4_CUSTOM_MAIN_MODE_MCS          <<16 | (PX4_CUSTOM_SUB_MODE_MCS_MANUAL         << 24 ),
        MCS_STAB            = PX4_CUSTOM_MAIN_MODE_MCS          <<16 | (PX4_CUSTOM_SUB_MODE_MCS_STAB           << 24 ),
        HUMAN_STAB          = PX4_CUSTOM_MAIN_MODE_HUMAN_STAB   <<16,
        HUMAN_COG           = PX4_CUSTOM_MAIN_MODE_HUMAN_COG    <<16,
    };
};
